import Home from "@partial/Homepage/Home";
import { Metadata } from "next";
import dynamic from "next/dynamic";
import { Fragment } from "react";

export const metadata: Metadata = {
  title: "Muhammad Naufal Yafi' - Frontend Developer | Portfolio",
  description: "Generated by create next app",
};

const TechStack = dynamic(() => import("@partial/Homepage/TechStack"));
const MyName = dynamic(() => import("@partial/Homepage/MyName"));
const Projects = dynamic(() => import("@partial/Homepage/Projects"));
const GithubActivity = dynamic(() => import("@partial/Homepage/GithubActivity"));
const Writing = dynamic(() => import("@partial/Homepage/Writing"));

export default function RootApp() {
  return (
    <Fragment>
      <Home />
      <TechStack />
      <MyName />
      <Projects />
      <GithubActivity />
      <Writing />
    </Fragment>
  );
}
