import Home from "@partial/Homepage/Home";
import {
  ProjectsDesktopView,
  ProjectsMobileView,
} from "@partial/Homepage/Projects";
import { Metadata } from "next";
import dynamic from "next/dynamic";
import { Fragment } from "react";

export const metadata: Metadata = {
  title: "Muhammad Naufal Yafi' - Frontend Developer | Portfolio",
  description: "Generated by create next app",
};

const TechStack = dynamic(() => import("@partial/Homepage/TechStack"));
const MyName = dynamic(() => import("@partial/Homepage/MyName"));
const GithubActivity = dynamic(
  () => import("@partial/Homepage/GithubActivity"),
);
const Writing = dynamic(() => import("@partial/Homepage/Writing"));
const Footer = dynamic(() => import("@partial/Footer"));

export default function RootApp() {
  return (
    <Fragment>
      <Home />
      <TechStack />
      <MyName />
      <div className="hidden lg:block">
        <ProjectsDesktopView />
      </div>
      <div className="block lg:hidden">
        <ProjectsMobileView />
      </div>
      <GithubActivity />
      <Writing />
      <Footer />
    </Fragment>
  );
}
